title: Awesome Food
author: Just Kidding
email: jkidding@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is about all the awesome food in Taiwan.

# social links
twitter_username: j_kidding # DO NOT include the @ character, or else the build will fail!
github_username:  j_kidding # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
